name: child_safety_app
description: Child Safety & Emotion Detection Mobile App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  http: ^1.1.0
  camera: ^0.10.5+2
  image_picker: ^0.8.7+1
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.5
  provider: ^6.0.0
  shared_preferences: ^2.2.1
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

